In [1]:
import imdb
import lstm

In [2]:
%load_ext autoreload
%autoreload 2

In [7]:
datasets = {'imdb': (imdb.load_data, imdb.prepare_data)}
load_data, prepare_data = imdb.load_data, imdb.prepare_data

In [8]:
n_words = 10000
maxlen = 100
train, valid, test = load_data(n_words=n_words, valid_portion=0.05, maxlen=maxlen)

In [15]:
lstm.get_minibatches_idx(10, 3)

[(0, array([0, 1, 2], dtype=int32)),
 (1, array([3, 4, 5], dtype=int32)),
 (2, array([6, 7, 8], dtype=int32)),
 (3, array([9], dtype=int32))]

In [27]:
prepare_data([train[0][1], train[0][2]], [train[1][1], train[1][2]], 20)

(array([[  16,    1],
        [ 586,    2],
        [  32,    1],
        [ 885,  139],
        [  17,    6],
        [  39,  130],
        [  68,    1],
        [  31,    5],
        [2994,    6],
        [2389,   25],
        [ 328,  105],
        [   4, 4730],
        [   0,   40]]), array([[ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 1.,  1.],
        [ 0.,  1.]], dtype=float32), [0, 0])

In [25]:
train[0][1]
train[1][1]

0

In [233]:
from neuralcraft import layers, optimizers, test

In [8]:
test.RNNTest()

without mask:
[ 2.63279891  0.          0.          0.        ]


TypeError: Condition given to the op has to be a scalar with 0 standing for False, anything else for True

In [64]:
a, b = [1, 2]

In [93]:
from theano import tensor as T

In [94]:
sc = T.scalar()

In [98]:
isinstance(sc, T.TensorVariable)

True

In [20]:
import theano
from theano import tensor as T
def sss():
  a = theano.shared(3.)
  return [[a, a * 2]]

In [24]:
b = T.scalar()
a = theano.shared(3.)
f = theano.function([b], b, updates=sss())

In [27]:
f(2)

array(2.0, dtype=float32)

In [166]:
a = np.array(3).astype('float32')

In [167]:
a.dtype

dtype('float32')

In [234]:
test.optimizerTest(optimizers.adagrad)

0.70279955864
[array([[ 1.96526492, -0.87820077],
       [-0.73007756,  0.27837306],
       [ 0.06517782, -0.90734345]], dtype=float32), array([ 1.6662879 ,  0.53066796], dtype=float32)]
0.690732657909
[array([[ 1.97215497, -0.88521755],
       [-0.72298741,  0.28538984],
       [ 0.07226034, -0.90032667]], dtype=float32), array([ 1.65965641,  0.53768474], dtype=float32)]


In [31]:
import numpy as np

In [176]:
a = theano.shared(np.ones((2,3)))
b = np.zeros_like(a.get_value())

In [ ]:
a.d

In [37]:
b

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [38]:
for a, b, c in zip([1, 2, 3], [2, 3, 4], [3, 4, 5]):
  print a, b, c

1 2 3
2 3 4
3 4 5


In [231]:
def check_update_order():
  a = theano.shared(1.)
  b = theano.shared(10.)
  xt = T.scalar()
  f = theano.function([xt], xt + a + b, updates=[[a, a+1.], [b, 2.*b*a]])
  return f, a, b
f, a, b = check_update_order()

In [232]:
print f(2), a.get_value(), b.get_value()

13.0 2.0 20.0


In [64]:
a.astype('float32')

Elemwise{Cast{float32}}.0

In [65]:
theano.shared(3, dtype='float32')

TypeError: No suitable SharedVariable constructor could be found. Are you sure all kwargs are supported? We do not support the parameter dtype or type. value="3". parameters="{'dtype': 'float32'}"

In [88]:
mt = T.matrix()
f = theano.function([mt], T.sqr(mt) + 1.)

In [89]:
f(np.array([[2, 3], [4, 5]], dtype='float32'))

array([[  5.,  10.],
       [ 17.,  26.]], dtype=float32)

In [188]:
type(np.float32(3.))

numpy.float32